// <auto-generated>
// This file is auto-generated by EventRegistryGenerator.
// Do not modify manually.
// </auto-generated>
#if ZENJECT
using Zenject;

namespace Rino.GameFramework.DDDCore
{
	/// <summary>
	/// 自動生成的 Event Installer，註冊此 Assembly 中的所有 IEvent 實作
	/// </summary>
	public class BuffSystemEventEventInstaller : Installer<BuffSystemEventEventInstaller>
	{
		public override void InstallBindings()
		{
			Container.BindMessageBroker<Rino.GameFramework.BuffSystem.BuffApplied>();
			Container.BindMessageBroker<Rino.GameFramework.BuffSystem.BuffRemoved>();
			Container.BindMessageBroker<Rino.GameFramework.BuffSystem.BuffStackChanged>();
		}
	}
}
#endif
