using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Compilation;

namespace Rino.GameFramework.DDDCore.Editor
{
	/// <summary>
	/// 自動掃描所有 IEvent 實作並為每個 Assembly 生成對應的 EventRegistrar
	/// </summary>
	[InitializeOnLoad]
	public static class EventRegistryGenerator
	{
		static EventRegistryGenerator()
		{
			CompilationPipeline.compilationFinished += OnCompilationFinished;
		}

		private static void OnCompilationFinished(object obj)
		{
			Generate();
		}

		[MenuItem("Tools/Generate Event Registrars")]
		public static void Generate()
		{
			var eventTypes = TypeCache.GetTypesDerivedFrom<IEvent>()
									  .Where(t => !t.IsAbstract && !t.IsInterface && !t.IsGenericType)
									  .Where(t => !IsTestAssembly(t.Assembly))
									  .ToList();

			// 按 Assembly 分組
			var groupedByAssembly = eventTypes.GroupBy(t => t.Assembly).ToList();

			var generatedCount = 0;

			foreach(var group in groupedByAssembly)
			{
				var assembly = group.Key;
				var types = group.OrderBy(t => t.FullName).ToList();

				var outputPath = GetOutputPath(assembly.GetName().Name);

				if(outputPath == null)
				{
					UnityEngine.Debug.LogWarning($"[EventRegistrar] Cannot find asmdef for assembly: {assembly.GetName().Name}");
					continue;
				}

				var className = GetClassName(assembly.GetName().Name);
				var code = GenerateCode(className, types);

				var directory = Path.GetDirectoryName(outputPath);

				if(!Directory.Exists(directory))
				{
					Directory.CreateDirectory(directory);
				}

				var existingContent = File.Exists(outputPath) ? File.ReadAllText(outputPath) : string.Empty;

				if(existingContent != code)
				{
					File.WriteAllText(outputPath, code);
					generatedCount++;
				}
			}

			if(generatedCount > 0)
			{
				AssetDatabase.Refresh();
				UnityEngine.Debug.Log($"[EventRegistrar] Generated {generatedCount} registrar(s) for {eventTypes.Count} event types.");
			}
		}

		private static bool IsTestAssembly(System.Reflection.Assembly assembly)
		{
			var name = assembly.GetName().Name;
			return name.Contains(".Tests") || name.EndsWith("Tests");
		}

		private static string GetOutputPath(string assemblyName)
		{
			// 找到對應的 asmdef 檔案
			var asmdefGuids = AssetDatabase.FindAssets($"t:AssemblyDefinitionAsset {assemblyName}");

			return (from guid in asmdefGuids
					select AssetDatabase.GUIDToAssetPath(guid) into path
					let fileName = Path.GetFileNameWithoutExtension(path)
					where fileName == assemblyName
					select Path.GetDirectoryName(path) into directory
					select Path.Combine(directory, "Installer", "EventInstaller.g.cs")).FirstOrDefault();
		}

		private static string GetClassName(string assemblyName)
		{
			// 移除前綴和點，轉換為 PascalCase
			// 例如 "Rino.DDDCore.Domain" -> "DDDCoreDomainEventInstaller"
			var parts = assemblyName.Split('.');
			var relevantParts = parts.SkipWhile(p => p == "Rino").ToList();

			var name = string.Join("", relevantParts.Select(ToPascalCase));
			return $"{name}EventInstaller";
		}

		private static string ToPascalCase(string input)
		{
			if(string.IsNullOrEmpty(input)) return input;

			return char.ToUpper(input[0]) + input.Substring(1);
		}

		private static string GenerateCode(string className, List<Type> eventTypes)
		{
			var lines = eventTypes.Select(t => $"\t\t\tContainer.BindMessageBroker<{t.FullName.Replace("+", ".")}>();");

			return $@"// <auto-generated>
// This file is auto-generated by EventRegistryGenerator.
// Do not modify manually.
// </auto-generated>
#if ZENJECT
using Zenject;

namespace Rino.GameFramework.DDDCore
{{
	/// <summary>
	/// 自動生成的 Event Installer，註冊此 Assembly 中的所有 IEvent 實作
	/// </summary>
	public class {className} : Installer<{className}>
	{{
		public override void InstallBindings()
		{{
{string.Join("\n", lines)}
		}}
	}}
}}
#endif
";
		}
	}
}